Let standard domain (/var)/run/cups/cups.sock be used if available
Now, if there is not already a CUPS running (for example from .deb
packages), the Snap's CUPS uses the standard domain socket
(/var)/run/cups/cups.sock and the standard port 631. If domain socket
or port are already occupied the alternatives
/var/snap/printing-stack-snap/common/run/cups.sock and port 10631 are
used.

To make this Snap's tools always use this Snap's CUPS, the actually
selected domain socket is set as ServerName in the Snap's client.conf,
/var/snap/printing-stack-snap/common/etc/cups/client.conf and libcups
is built to use this client.conf by default.

This Snap's cups-browsed is started with the CUPS_SERVER environment
variable set to the selected domain socket. So it always attaches to
the CUPS of this Snap.

Further changes and fixes to make this working and to make this Snap
also correctly working with the extra check of administrative tasks of
the previous commit:

- All apps which do admin tasks via cupsd (cups-browsed, lpadmin,
  cupsenable, cupsdisable, cupsaccept, cupsreject, cancel, cupsctl)
  are now plugging cups-control.

- A new interface "cups-domain-socket" based on the "system-files"
  interface allows the Snap's apps to read/write access the standard
  CUPS domain socket (/var)/run/cups/cups.sock.

- The CUPS build system is patched to use
  /var/snap/printing-stack-snap/common/etc/cups instead of /etc/cups
  as standard CUPS_SERVERROOT, especially to make libcups use the
  Snap's client.conf.

- run-cupsd checks whether the standard CUPS domain socket is free
  using the "lsof" utility. Then it drops the selected domain socket
  as ServerName in client.conf, so that the utilities use it.

- run-cups-browsed reads the domain socket from client.conf and sets
  the CUPS_SERVER environment variable before starting cups-browsed.
  run-cups-browsed waits for cupsd coming up, by checking the presence
  of the PID file and whether there is actually a process with this
  PID.  Only then it reads client.conf, to be sure it contains the
  currently selected domain socket.

- run-cupsd and run-cups-browsed delete their PID files in the end, as
  when they end, their corresponding daemon has terminated.

- Fixed the PID file paths in stop-cupsd and stop-cups-browsed.

- Changed the location for CUPS config files to
  /var/snap/printing-stack-snap/common/etc/cups

diff --git a/scripts/run-cups-browsed b/scripts/run-cups-browsed
--- a/scripts/run-cups-browsed
+++ b/scripts/run-cups-browsed
@@ -5,11 +5,11 @@ set -e -x
 mkdir -p $SNAP_DATA/var/log
 mkdir -p $SNAP_DATA/var/cache
 mkdir -p $SNAP_DATA/var/run
-mkdir -p $SNAP_COMMON/etc
+mkdir -p $SNAP_COMMON/etc/cups
 
-CONF=$SNAP_COMMON/etc/cups-browsed.conf
+CONF=$SNAP_COMMON/etc/cups/cups-browsed.conf
+CLIENTCONF=$SNAP_COMMON/etc/cups/client.conf
 DAEMON=cups-browsed
-DOMAINSOCKET=$SNAP_DATA/var/run/cups.sock
 
 # Set UTF-8
 export LC_ALL=C.UTF-8
@@ -35,8 +35,32 @@ mkdir -p $TMPDIR
 #export CUPS_FONTPATH=$SNAP_DATA/share/cups/fonts
 #export CUPS_REQUESTROOT=$SNAP_DATA/var/spool
 #export CUPS_SERVERBIN=$SNAP_DATA/lib/cups
-#export CUPS_SERVERROOT=$SNAP_COMMON/etc
+#export CUPS_SERVERROOT=$SNAP_COMMON/etc/cups
 #export CUPS_STATEDIR=$SNAP_DATA/var/run
+
+# Wait for this Snap's CUPS coming up before preparing
+# cups-browsed.conf and starting cups-browsed, to assure
+# that it attaches to the correct CUPS
+CUPSSTARTED=0
+for i in $(seq 60); do
+    if [ -r ${SNAP_DATA}/var/run/cupsd.pid ]; then
+	PID=$(cat "${SNAP_DATA}/var/run/cupsd.pid" || true)
+	if [ -n "${PID}" ] && kill -0 "${PID}" 2>/dev/null; then
+	    CUPSSTARTED=1
+	    break;
+	fi
+    fi
+    sleep 1
+done
+if [ "${CUPSSTARTED}" = "0" ]; then
+    echo "ERROR: CUPS startup timed out"
+    exit 1
+fi
+
+# Read domain socket from CUPS' client.conf
+DOMAINSOCKET=`grep -i ServerName $CLIENTCONF | cut -d ' ' -f 2`
+
+export CUPS_SERVER=$DOMAINSOCKET
 
 # Create cups-browsed.conf if not already present
 if  [ ! -f $CONF ]; then
@@ -64,3 +88,6 @@ echo $PID > $SNAP_DATA/var/run/cups-browsed.pid
 
 # Keep this script running until cups-browsed terminates
 wait $PID
+
+# Remove PID file as process is done
+rm -f $SNAP_DATA/var/run/cups-browsed.pid
